# This is the way to use make with docker
sudo: required
services:
  - docker
env:
  - TAGS=$TRAVIS_BRANCH;
script:
# Run all tests in this directory recursively
  - make test

after_success:
  - if [[ "$TRAVIS_TAG" != '' ]]; then
      make deploy;
    fi
