apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 1
  minReadySeconds: 1
  template:
    metadata:
      labels:
        application: node-sample
    spec:
      containers:
      - name: node-container
        #image: mycluster.icp:8500/default/node_sample:local
        image: 192.168.99.100:32767/default/node-sample:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3030
