apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  replicas: 1
  minReadySeconds: 1
  template:
    metadata:
      labels:
        application: identity
    spec:
      containers:
      - name: identity-container
        image: cloudagility/identity_microservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3030