apiVersion: v1
kind: Service
metadata:
  name: identity-service
  labels:
    service: identity
spec:
  type: NodePort
  ports:
  - port: 3030
    nodePort: 30001
    protocol: TCP
  selector:
    application: identity