apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    service: node
spec:
  type: NodePort
  ports:
  - port: 3030
    nodePort: 30030
    protocol: TCP
  selector:
    application: node-sample
